### ISSUE TITLE
Missing ndarray dev dependency

### ISSUE THREAD

**Issue by rreusser** [scijs/ndarray-complex#2]
`npm install && npm test` fails because `ndarray` isn't included as a dev dependency. I can fix this totally trivially, but if I'm gonna contribute, I'd like to get into a pattern where I don't have to fudge a bunch of stuff. I'm newish to the node world. Is there a way to fix this aside from adding the dev dependency and submitting a pull request?

**Comment by mikolalysenko** [comment]
I think a PR is the best way to do it, if you send me a patch I can just merge it in later on tonight (going to be driving all day).
