### ISSUE TITLE
Division isn't floating-point-friendly

### ISSUE THREAD

**Issue by rreusser** [scijs/ndarray-complex#3]
A number of the division functions calculate the modulus:

```javascript
var w = s_r * s_r + s_i * s_i
```

It's not the worst thing ever, but if it's the basis for other stuff, it would probably be good to rework that to prevent avoidable overflow errors. See: [Numerical Recipes](https://books.google.com/books?id=1aAOdzK3FegC&pg=PA226&lpg=PA226&dq=complex+division+underflow&source=bl&ots=3jPhF9Irii&sig=JwEAckqmfBNd8dIQTrUD-Pk9dzE&hl=en&sa=X&ei=-VZQVYDpJImRyATAoYCwBg&ved=0CDwQ6AEwBA#v=onepage&q=complex%20division%20underflow&f=false)

**Comment by mikolalysenko** [comment]
Should be fixed now, thanks.
